### ISSUE TITLE
Downloading single cell force directed layout images

### ISSUE THREAD

**Issue by AbbyKimball** [nolanlab/vortex#1]
Hello! 

I'm trying to find a way to download the single cell force directed layout as an image. When I select "Export Image" and save it to my desktop it doesn't appear. In fact, I can't find it anywhere on my computer.
<img width="1287" alt="screen shot 2016-12-27 at 11 35 02 am" src="https://cloud.githubusercontent.com/assets/24797260/21505886/c2e3fa36-cc28-11e6-9107-12c4c775142d.png">
<img width="1141" alt="screen shot 2016-12-27 at 11 35 35 am" src="https://cloud.githubusercontent.com/assets/24797260/21505888/c3d0dc34-cc28-11e6-97f3-488e360193ed.png">

When I try to save it in a folder on my desktop...

<img width="1200" alt="screen shot 2016-12-27 at 11 37 12 am" src="https://cloud.githubusercontent.com/assets/24797260/21505896/ddd8984c-cc28-11e6-8662-e48f49700a35.png">

The folder shows up on my desktop, but it is empty.

<img width="1306" alt="screen shot 2016-12-27 at 11 38 06 am" src="https://cloud.githubusercontent.com/assets/24797260/21505905/f31be830-cc28-11e6-9ff1-692b2f9deee0.png">

Thanks :)

**Comment by nsamusik** [comment]
Fixed!
