### ISSUE TITLE
Exporting clustering results

### ISSUE THREAD

**Issue by AndyinMission** [nolanlab/vortex#3]
Hi, it seems the exported fcs files are DATATYPE/D.  I'd really like to use flowCore down-stream to allow adding the cluster IDs to an Imagestream dataset using R integration in FCS express.  However, flowCore isn't reading the DATATYPE/D files.  Flowjo also seems to not be scaling or exporting them correctly.

Ideally, it would be nice to be able to either 1) export multiple csv files, one for each input fcs file in the data set or 2) export DATATYPE/F fcs files that are more readily handled by existing flow cytometry packages.  

Edit - FCS Express throws an error message when trying to open the exported FCS files from Vortex (attached).

![error](https://cloud.githubusercontent.com/assets/11186274/23370257/c316d046-fcd9-11e6-96bf-1ee454e7e983.png)

Thanks.

**Comment by nsamusik** [comment]
Hi Andy, 

I switched away from Cytobank to the FlowCyt library and now VorteX should be writing in DATATYPE/F format. Please give it a try and let me know how it goes. Thanks very much for pointing out the problem

https://github.com/nolanlab/vortex/releases/tag/27-Feb-2017

Best,

Nikolay

**Comment by AndyinMission** [comment]
Excellent, thanks.
