### ISSUE TITLE
Some Problems about X-shift standalone 

### ISSUE THREAD

**Issue by poipou** [nolanlab/vortex#4]
Hi , I like the X-shift very much!
However, the X-shift standalone version can't output a F format DataType for flowCore. Whether it's possible to update the standalone version?
Another question, when I testing the data BM2_cct_normalized_01_non-Neutrophils.fcs using X-shift, the result .fcs file can only get one cluster.I don't know what happened.

**Comment by nsamusik** [comment]
Dear poipu,

Thank you! I changed the Standalone version to output the FCS files as DATATYPE/F, it should be working now. Please check the latest release - VorteX 29-Jun-2017

**Comment by poipou** [comment]
Thank you! It works
